// Generated by LiveScript 1.3.1
/*
table disqus
  key serial primary key,
  url text,
  slug text,
  ispublic boolean,
  moderate boolean default true

table comment
  key serial primary key,
  disqus int references disqus(key),
  owner int references users(key),
  createdtime timestamp default now(),
  modifiedtime timestamp default now(),
  reply int references comment(key),
  content text,
  state text,
  deleted boolean
*/
api.post('/disqus/', engine.multi.parser, function(req, res){
  var owner;
  if (!req.user || !req.user.key) {
    return aux.r400(res);
  }
  owner = req.user.key;
  return io.query("insert into comment (owner,createdtime,reply,content) values ($1, $2, $3, $4)", [owner, Date.now(), reply, content]).then(function(){
    return res.send();
  })['catch'](aux.errorHandler(res));
});
api['delete']('/disqus/:key', authorized(function(req, res){
  if (!req.params.id || isNaN(req.params.id)) {
    return aux.r400(res);
  }
  return io.query("select key from comment where key = $1", [key]).then(function(){
    return res.send();
  })['catch'](aux.errorHandler(res));
}));
api.get('/disqus/:key', function(req, res){
  return io.query("select * from disqus where slug = $1", [slug]).then(function(r){
    var disqus;
    r == null && (r = {});
    if (!(disqus = (r.rows || (r.rows = []))[0])) {
      return [];
    }
    return io.query("select * from comment where disqus = $1 order by createdtimea", [disqus.key]);
  }).then(function(r){
    r == null && (r = {});
    return res.send(r.rows || []);
  })['catch'](aux.errorHandler(res));
});